# Book settings
title: Follow the grant - Research Recipies
author: Hristio 
logo: imgs/logo.png
copyright: 2024
only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/InvestigatingScience/research_recipies_workbook 
  path_to_book: docs 
  branch: main

# Add GitHub buttons to your book
html:
  use_repository_button: true

launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://mybinder.org"
  thebe: true


# Thebe configuration
thebe:
  repository_url: "https://github.com/InvestigatingScience/research_recipies_workbook"
  branch: "main"
  selector: ".cell"  # Automatically make all code cells interactive
  kernel_name: "python3"


